version: '3'
services:

  web:
    container_name: web
    build: ./web
    ports:
     - "80:80"
     - "443:443"
     - "6379:6379"
    volumes:
     - ./logs:/var/log
     - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./web/nginx/sites-enabled/:/etc/nginx/sites-enabled
volumes:
  data-volume: